const SET_USER = 'SET_USER';
const SET_SOCKET = 'SET_SOCKET';
const UPDATE_ITEMS_LIST = 'UPDATE_ITEMS_LIST';
const SUBMIT_ITEM = 'SUBMIT_ITEM';
const COMPLETE_ITEM = 'COMPLETE_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';

export {
  SET_USER,
  SET_SOCKET,
  UPDATE_ITEMS_LIST,
  SUBMIT_ITEM,
  COMPLETE_ITEM,
  DELETE_ITEM
};